/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Camara.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Camara(props) {
  const { nodes, materials } = useGLTF('/components/Camara.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Camera_01_strap.geometry} material={materials.Camera_01_strap} />
      <mesh geometry={nodes.Mesh016.geometry} material={materials.Camera_01_lens_body} />
      <mesh geometry={nodes.Mesh016_1.geometry} material={materials.Camera_01_lens} />
      <mesh geometry={nodes.Mesh016_2.geometry} material={materials.Camera_01_body} />
      <mesh geometry={nodes.Mesh016_3.geometry} material={materials.Camera_01_strap} />
    </group>
  )
}

useGLTF.preload('/components/Camara.gltf')
