/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Cuadro.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cuadro(props) {
  const { nodes, materials } = useGLTF('/components/Cuadro/Cuadro.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.postcard_01.geometry} material={materials.postcard_set_01} position={[0, 0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_02.geometry} material={materials.postcard_set_01} position={[0.17, 0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_03.geometry} material={materials.postcard_set_01} position={[0.34, 0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_04.geometry} material={materials.postcard_set_01} position={[0.51, 0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_05.geometry} material={materials.postcard_set_01} position={[0, 0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_06.geometry} material={materials.postcard_set_01} position={[0.17, 0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_07.geometry} material={materials.postcard_set_01} position={[0.34, 0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_08.geometry} material={materials.postcard_set_01} position={[0.51, 0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_09.geometry} material={materials.postcard_set_01} position={[0, 0, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_10.geometry} material={materials.postcard_set_01} position={[0.17, 0, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_11.geometry} material={materials.postcard_set_01} position={[0.34, 0, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_12.geometry} material={materials.postcard_set_01} position={[0.51, 0, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_13.geometry} material={materials.postcard_set_01} position={[0, -0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_14.geometry} material={materials.postcard_set_01} position={[0.17, -0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_15.geometry} material={materials.postcard_set_01} position={[0.34, -0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_16.geometry} material={materials.postcard_set_01} position={[0.51, -0.11, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_17.geometry} material={materials.postcard_set_01} position={[0, -0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_18.geometry} material={materials.postcard_set_01} position={[0.17, -0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_19.geometry} material={materials.postcard_set_01} position={[0.34, -0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.postcard_20.geometry} material={materials.postcard_set_01} position={[0.51, -0.22, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/components/Cuadro/Cuadro.gltf')
